//
//  FramesJson.swift
//  CollageMaker
//
//  Created by M!L@N on 29/02/24.
//  Copyright © 2024 iMac. All rights reserved.
//

import Foundation

let allFramesJson = [
    [["image": 1, "parts": 1],
     ["image": 2, "parts": 2],
     ["image": 3, "parts": 2],
     ["image": 4, "parts": 3],
     ["image": 5, "parts": 3],
     ["image": 6, "parts": 3],
     ["image": 7, "parts": 2],
     ["image": 8, "parts": 2],
     ["image": 9, "parts": 4],
     ["image": 10, "parts": 4],
     ["image": 11, "parts": 3],
     ["image": 12, "parts": 4],
     ["image": 13, "parts": 4],
     ["image": 14, "parts": 4],
     ["image": 15, "parts": 4],
     ["image": 16, "parts": 4],
     ["image": 17, "parts": 6],
     ["image": 18, "parts": 6],
//     ["image": 19, "parts": 3],
//     ["image": 20, "parts": 3],
     ["image": 21, "parts": 4],
     ["image": 22, "parts": 4],
     ["image": 23, "parts": 5],
     ["image": 24, "parts": 5]],
    
    [["image": 25, "parts": 2],
     ["image": 26, "parts": 2],
     ["image": 27, "parts": 2],
     ["image": 28, "parts": 2],
     ["image": 29, "parts": 3],
     ["image": 30, "parts": 3],
     ["image": 31, "parts": 3],
     ["image": 32, "parts": 3],
     ["image": 33, "parts": 3],
     ["image": 34, "parts": 3],
     ["image": 35, "parts": 3],
     ["image": 36, "parts": 3],
     ["image": 37, "parts": 3],
     ["image": 38, "parts": 3],
     ["image": 39, "parts": 3],
     ["image": 40, "parts": 3],
     ["image": 41, "parts": 3],
     ["image": 42, "parts": 3],
     ["image": 43, "parts": 4],
     ["image": 44, "parts": 4],
     ["image": 45, "parts": 3],
//     ["image": 46, "parts": 3],
//     ["image": 47, "parts": 6],
//     ["image": 48, "parts": 6]
    ],
    
    [["image": 49, "parts": 4],
     ["image": 50, "parts": 4],
     ["image": 51, "parts": 4],
     ["image": 52, "parts": 4],
     ["image": 53, "parts": 4],
     ["image": 54, "parts": 4],
     ["image": 55, "parts": 5],
     ["image": 56, "parts": 5],
     ["image": 57, "parts": 5],
     ["image": 58, "parts": 5],
     ["image": 59, "parts": 5],
     ["image": 60, "parts": 5],
     ["image": 61, "parts": 5],
     ["image": 62, "parts": 5],
     ["image": 63, "parts": 6],
     ["image": 64, "parts": 6],
     ["image": 65, "parts": 3],
     ["image": 66, "parts": 3],
     ["image": 67, "parts": 3],
     ["image": 68, "parts": 3],
     ["image": 69, "parts": 3],
     ["image": 70, "parts": 3],
     ["image": 71, "parts": 4],
     ["image": 72, "parts": 4]],
    
    [["image": 73, "parts": 4],
     ["image": 74, "parts": 4],
     ["image": 75, "parts": 4],
     ["image": 76, "parts": 4],
     ["image": 77, "parts": 4],
     ["image": 78, "parts": 4],
     ["image": 79, "parts": 4],
     ["image": 80, "parts": 4],
     ["image": 81, "parts": 5],
     ["image": 82, "parts": 5],
     ["image": 83, "parts": 5],
     ["image": 84, "parts": 5],
     ["image": 85, "parts": 5],
     ["image": 86, "parts": 5],
     ["image": 87, "parts": 5],
     ["image": 88, "parts": 5],
     ["image": 89, "parts": 3],
     ["image": 90, "parts": 3],
     ["image": 91, "parts": 3],
     ["image": 92, "parts": 3],
     ["image": 93, "parts": 4],
     ["image": 94, "parts": 4],
     ["image": 95, "parts": 3],
     ["image": 96, "parts": 3]],
    
    [["image": 97, "parts": 5],
     ["image": 98, "parts": 5],
     ["image": 99, "parts": 6],
     ["image": 100, "parts": 6],
     ["image": 101, "parts": 6],
     ["image": 102, "parts": 6],
     ["image": 103, "parts": 6],
     ["image": 104, "parts": 6],
     ["image": 105, "parts": 6],
     ["image": 106, "parts": 6],
     ["image": 107, "parts": 6],
     ["image": 108, "parts": 6],
     ["image": 109, "parts": 6],
     ["image": 110, "parts": 6],
     ["image": 111, "parts": 6],
     ["image": 112, "parts": 6],
     ["image": 113, "parts": 3],
     ["image": 114, "parts": 3],
     ["image": 115, "parts": 4],
     ["image": 116, "parts": 4],
     ["image": 117, "parts": 3],
     ["image": 118, "parts": 3],
     ["image": 119, "parts": 3],
     ["image": 120, "parts": 3]],
    
    [["image": 121, "parts": 5],
     ["image": 122, "parts": 5],
     ["image": 123, "parts": 6],
     ["image": 124, "parts": 6],
     ["image": 125, "parts": 5],
     ["image": 126, "parts": 5],
     ["image": 127, "parts": 7],
     ["image": 128, "parts": 7],
     ["image": 129, "parts": 6],
     ["image": 130, "parts": 6],
     ["image": 131, "parts": 7],
     ["image": 132, "parts": 7],
     ["image": 133, "parts": 6],
     ["image": 134, "parts": 6],
     ["image": 135, "parts": 6],
     ["image": 136, "parts": 6],
     ["image": 137, "parts": 4],
     ["image": 138, "parts": 4],
     ["image": 139, "parts": 4],
     ["image": 140, "parts": 5],
     ["image": 141, "parts": 5],
     ["image": 142, "parts": 5],
     ["image": 143, "parts": 3],
     ["image": 144, "parts": 3]],
    
    [["image": 145, "parts": 6],
     ["image": 146, "parts": 6],
     ["image": 147, "parts": 6],
     ["image": 148, "parts": 6],
     ["image": 149, "parts": 7],
     ["image": 150, "parts": 7],
     ["image": 151, "parts": 7],
     ["image": 152, "parts": 7],
     ["image": 153, "parts": 7],
     ["image": 154, "parts": 7],
     ["image": 155, "parts": 7],
     ["image": 156, "parts": 7],
     ["image": 157, "parts": 7],
     ["image": 158, "parts": 8],
     ["image": 159, "parts": 8],
     ["image": 160, "parts": 8],
//     ["image": 161, "parts": 4],
//     ["image": 162, "parts": 4],
//     ["image": 163, "parts": 4],
//     ["image": 164, "parts": 4],
//     ["image": 165, "parts": 5],
//     ["image": 166, "parts": 5],
//     ["image": 167, "parts": 5],
//     ["image": 168, "parts": 5]
    ],
    
    [["image": 169, "parts": 7],
     ["image": 170, "parts": 7],
     ["image": 171, "parts": 6],
     ["image": 172, "parts": 6],
     ["image": 173, "parts": 7],
     ["image": 174, "parts": 7],
     ["image": 175, "parts": 7],
     ["image": 176, "parts": 7],
     ["image": 177, "parts": 7],
     ["image": 178, "parts": 8],
     ["image": 179, "parts": 7],
     ["image": 180, "parts": 7],
     ["image": 181, "parts": 8],
     ["image": 182, "parts": 8],
     ["image": 183, "parts": 8],
     ["image": 184, "parts": 8],
//     ["image": 185, "parts": 5],
//     ["image": 186, "parts": 5],
//     ["image": 187, "parts": 5],
//     ["image": 188, "parts": 6],
//     ["image": 189, "parts": 7],
//     ["image": 190, "parts": 7],
//     ["image": 191, "parts": 9],
//     ["image": 192, "parts": 7]
    ],
    
    [["image": 193, "parts": 7],
//     ["image": 194, "parts": 9],
//     ["image": 195, "parts": 9],
     ["image": 196, "parts": 7],
     ["image": 197, "parts": 7],
     ["image": 198, "parts": 7],
     ["image": 199, "parts": 7],
     ["image": 200, "parts": 7],
     ["image": 201, "parts": 7],
     ["image": 202, "parts": 7],
     ["image": 203, "parts": 8],
     ["image": 204, "parts": 8],
     ["image": 205, "parts": 7],
     ["image": 206, "parts": 7],
     ["image": 207, "parts": 9],
     ["image": 208, "parts": 9],
     ["image": 209, "parts": 9],
     ["image": 210, "parts": 9],
//     ["image": 211, "parts": 8],
//     ["image": 212, "parts": 8],
//     ["image": 213, "parts": 5],
//     ["image": 214, "parts": 5],
//     ["image": 215, "parts": 12],
//     ["image": 216, "parts": 12]
    ],
    
    [["image": 217, "parts": 8],
     ["image": 218, "parts": 8],
     ["image": 219, "parts": 10],
     ["image": 220, "parts": 12],
     ["image": 221, "parts": 10],
     ["image": 222, "parts": 10],
     ["image": 223, "parts": 12],
     ["image": 224, "parts": 10],
     ["image": 225, "parts": 11],
     ["image": 226, "parts": 11],
     ["image": 227, "parts": 12],
     ["image": 228, "parts": 12],
     ["image": 229, "parts": 14],
     ["image": 230, "parts": 14],
     ["image": 231, "parts": 13],
     ["image": 232, "parts": 13],
//     ["image": 233, "parts": 12],
//     ["image": 234, "parts": 12],
//     ["image": 235, "parts": 13],
//     ["image": 236, "parts": 16],
     ["image": 237, "parts": 13],
     ["image": 238, "parts": 15],
     ["image": 239, "parts": 15],
     ["image": 240, "parts": 13]],
    
    [["image": 241, "parts": 16],
     ["image": 242, "parts": 16],
     ["image": 243, "parts": 16],
     ["image": 244, "parts": 16],
     ["image": 245, "parts": 16],
     ["image": 246, "parts": 16],
     ["image": 247, "parts": 16],
     ["image": 248, "parts": 16],
     ["image": 249, "parts": 16],
     ["image": 250, "parts": 14],
     ["image": 251, "parts": 14],
     ["image": 252, "parts": 13],
     ["image": 253, "parts": 13],
     ["image": 254, "parts": 13],
     ["image": 255, "parts": 11],
     ["image": 256, "parts": 11],
     ["image": 257, "parts": 10],
     ["image": 258, "parts": 10],
     ["image": 259, "parts": 10],
     ["image": 260, "parts": 10],
     ["image": 261, "parts": 10],
     ["image": 262, "parts": 10],
     ["image": 263, "parts": 10],
     ["image": 264, "parts": 10]],
    
    [["image": 265, "parts": 9],
     ["image": 266, "parts": 9],
     ["image": 267, "parts": 9],
     ["image": 268, "parts": 9],
     ["image": 269, "parts": 9],
     ["image": 270, "parts": 9],
     ["image": 271, "parts": 9],
     ["image": 272, "parts": 9],
     ["image": 273, "parts": 9],
     ["image": 274, "parts": 9],
     ["image": 275, "parts": 9],
     ["image": 276, "parts": 9],
     ["image": 277, "parts": 9],
     ["image": 278, "parts": 9],
     ["image": 279, "parts": 9],
     ["image": 280, "parts": 8],
     ["image": 281, "parts": 8],
     ["image": 282, "parts": 8],
     ["image": 283, "parts": 8],
     ["image": 284, "parts": 8],
     ["image": 285, "parts": 8],
     ["image": 286, "parts": 7],
     ["image": 287, "parts": 7],
     ["image": 288, "parts": 4]],
    
    [["image": 289, "parts": 17],
     ["image": 290, "parts": 17],
//     ["image": 291, "parts": 17],
//     ["image": 292, "parts": 17],
     ["image": 293, "parts": 18],
     ["image": 294, "parts": 18],
     ["image": 295, "parts": 19],
     ["image": 296, "parts": 19],
     ["image": 297, "parts": 19],
     ["image": 298, "parts": 19],
     ["image": 299, "parts": 21],
     ["image": 300, "parts": 21],
     ["image": 301, "parts": 21],
     ["image": 302, "parts": 24],
     ["image": 303, "parts": 24],
     ["image": 304, "parts": 25],
     ["image": 305, "parts": 2],
     ["image": 306, "parts": 2],
     ["image": 307, "parts": 2],
     ["image": 308, "parts": 2],
     ["image": 309, "parts": 3],
     ["image": 310, "parts": 3],
     ["image": 311, "parts": 3],
     ["image": 312, "parts": 3]]
]

let allHomeScreenFramesJson = ["1":
                                [["image": 1, "parts": 1],
                                 ["image": 2, "parts": 2],
                                 ["image": 3, "parts": 2],
                                 ["image": 4, "parts": 3],
                                 ["image": 5, "parts": 3],
                                 ["image": 6, "parts": 3],
                                 ["image": 7, "parts": 2],
                                 ["image": 8, "parts": 2],
                                 ["image": 9, "parts": 4],
                                 ["image": 10, "parts": 4],
                                 ["image": 11, "parts": 3],
                                 ["image": 12, "parts": 4],
                                 ["image": 13, "parts": 4],
                                 ["image": 14, "parts": 4],
                                 ["image": 15, "parts": 4],
                                 ["image": 16, "parts": 4],
                                 ["image": 17, "parts": 6, "isPremium": 1],
                                 ["image": 18, "parts": 6, "isPremium": 1],
//                                 ["image": 19, "parts": 3, "isPremium": 1],
//                                 ["image": 20, "parts": 3, "isPremium": 1],
                                 ["image": 21, "parts": 4, "isPremium": 1],
                                 ["image": 22, "parts": 4, "isPremium": 1],
                                 ["image": 23, "parts": 5, "isPremium": 1],
                                 ["image": 24, "parts": 5, "isPremium": 1]],
                               
                               "2": [["image": 25, "parts": 2],
                                     ["image": 26, "parts": 2],
                                     ["image": 27, "parts": 2],
                                     ["image": 28, "parts": 2],
                                     ["image": 29, "parts": 3],
                                     ["image": 30, "parts": 3],
                                     ["image": 31, "parts": 3],
                                     ["image": 32, "parts": 3],
                                     ["image": 33, "parts": 3],
                                     ["image": 34, "parts": 3],
                                     ["image": 35, "parts": 3],
                                     ["image": 36, "parts": 3],
                                     ["image": 37, "parts": 3],
                                     ["image": 38, "parts": 3],
                                     ["image": 39, "parts": 3],
                                     ["image": 40, "parts": 3],
                                     ["image": 41, "parts": 3, "isPremium": 1],
                                     ["image": 42, "parts": 3, "isPremium": 1],
                                     ["image": 43, "parts": 4, "isPremium": 1],
                                     ["image": 44, "parts": 4, "isPremium": 1],
                                     ["image": 45, "parts": 3, "isPremium": 1],
//                                     ["image": 46, "parts": 3, "isPremium": 1],
//                                     ["image": 47, "parts": 6, "isPremium": 1],
//                                     ["image": 48, "parts": 6, "isPremium": 1]
                                    ],
                               
                               "3": [["image": 49, "parts": 4],
                                     ["image": 50, "parts": 4],
                                     ["image": 51, "parts": 4],
                                     ["image": 52, "parts": 4],
                                     ["image": 53, "parts": 4],
                                     ["image": 54, "parts": 4],
                                     ["image": 55, "parts": 5],
                                     ["image": 56, "parts": 5],
                                     ["image": 57, "parts": 5],
                                     ["image": 58, "parts": 5],
                                     ["image": 59, "parts": 5],
                                     ["image": 60, "parts": 5],
                                     ["image": 61, "parts": 5],
                                     ["image": 62, "parts": 5],
                                     ["image": 63, "parts": 6],
                                     ["image": 64, "parts": 6],
                                     ["image": 65, "parts": 3, "isPremium": 1],
                                     ["image": 66, "parts": 3, "isPremium": 1],
                                     ["image": 67, "parts": 3, "isPremium": 1],
                                     ["image": 68, "parts": 3, "isPremium": 1],
                                     ["image": 69, "parts": 3, "isPremium": 1],
                                     ["image": 70, "parts": 3, "isPremium": 1],
                                     ["image": 71, "parts": 4, "isPremium": 1],
                                     ["image": 72, "parts": 4, "isPremium": 1]],
                               
                               "4": [["image": 73, "parts": 4],
                                     ["image": 74, "parts": 4],
                                     ["image": 75, "parts": 4],
                                     ["image": 76, "parts": 4],
                                     ["image": 77, "parts": 4],
                                     ["image": 78, "parts": 4],
                                     ["image": 79, "parts": 4],
                                     ["image": 80, "parts": 4],
                                     ["image": 81, "parts": 5],
                                     ["image": 82, "parts": 5],
                                     ["image": 83, "parts": 5],
                                     ["image": 84, "parts": 5],
                                     ["image": 85, "parts": 5],
                                     ["image": 86, "parts": 5],
                                     ["image": 87, "parts": 5],
                                     ["image": 88, "parts": 5],
                                     ["image": 89, "parts": 3, "isPremium": 1],
                                     ["image": 90, "parts": 3, "isPremium": 1],
                                     ["image": 91, "parts": 3, "isPremium": 1],
                                     ["image": 92, "parts": 3, "isPremium": 1],
                                     ["image": 93, "parts": 4, "isPremium": 1],
                                     ["image": 94, "parts": 4, "isPremium": 1],
                                     ["image": 95, "parts": 3, "isPremium": 1],
                                     ["image": 96, "parts": 3, "isPremium": 1]],
                               
                               "5": [["image": 97, "parts": 5],
                                     ["image": 98, "parts": 5],
                                     ["image": 99, "parts": 6],
                                     ["image": 100, "parts": 6],
                                     ["image": 101, "parts": 6],
                                     ["image": 102, "parts": 6],
                                     ["image": 103, "parts": 6],
                                     ["image": 104, "parts": 6],
                                     ["image": 105, "parts": 6],
                                     ["image": 106, "parts": 6],
                                     ["image": 107, "parts": 6],
                                     ["image": 108, "parts": 6],
                                     ["image": 109, "parts": 6],
                                     ["image": 110, "parts": 6],
                                     ["image": 111, "parts": 6],
                                     ["image": 112, "parts": 6],
                                     ["image": 113, "parts": 3, "isPremium": 1],
                                     ["image": 114, "parts": 3, "isPremium": 1],
                                     ["image": 115, "parts": 4, "isPremium": 1],
                                     ["image": 116, "parts": 4, "isPremium": 1],
                                     ["image": 117, "parts": 3, "isPremium": 1],
                                     ["image": 118, "parts": 3, "isPremium": 1],
                                     ["image": 119, "parts": 3, "isPremium": 1],
                                     ["image": 120, "parts": 3, "isPremium": 1]],
                               
                               "6": [["image": 121, "parts": 5],
                                     ["image": 122, "parts": 5],
                                     ["image": 123, "parts": 6],
                                     ["image": 124, "parts": 6],
                                     ["image": 125, "parts": 5],
                                     ["image": 126, "parts": 5],
                                     ["image": 127, "parts": 7],
                                     ["image": 128, "parts": 7],
                                     ["image": 129, "parts": 6],
                                     ["image": 130, "parts": 6],
                                     ["image": 131, "parts": 7],
                                     ["image": 132, "parts": 7],
                                     ["image": 133, "parts": 6],
                                     ["image": 134, "parts": 6],
                                     ["image": 135, "parts": 6],
                                     ["image": 136, "parts": 6],
                                     ["image": 137, "parts": 4, "isPremium": 1],
                                     ["image": 138, "parts": 4, "isPremium": 1],
                                     ["image": 139, "parts": 4, "isPremium": 1],
                                     ["image": 140, "parts": 5, "isPremium": 1],
                                     ["image": 141, "parts": 5, "isPremium": 1],
                                     ["image": 142, "parts": 5, "isPremium": 1],
                                     ["image": 143, "parts": 3, "isPremium": 1],
                                     ["image": 144, "parts": 3, "isPremium": 1]],
                               
                               "7": [["image": 145, "parts": 6],
                                     ["image": 146, "parts": 6],
                                     ["image": 147, "parts": 6],
                                     ["image": 148, "parts": 6],
                                     ["image": 149, "parts": 7],
                                     ["image": 150, "parts": 7],
                                     ["image": 151, "parts": 7],
                                     ["image": 152, "parts": 7],
                                     ["image": 153, "parts": 7],
                                     ["image": 154, "parts": 7],
                                     ["image": 155, "parts": 7],
                                     ["image": 156, "parts": 7],
                                     ["image": 157, "parts": 7],
                                     ["image": 158, "parts": 8],
                                     ["image": 159, "parts": 8],
                                     ["image": 160, "parts": 8],
//                                     ["image": 161, "parts": 4, "isPremium": 1],
//                                     ["image": 162, "parts": 4, "isPremium": 1],
//                                     ["image": 163, "parts": 4, "isPremium": 1],
//                                     ["image": 164, "parts": 4, "isPremium": 1],
//                                     ["image": 165, "parts": 5, "isPremium": 1],
//                                     ["image": 166, "parts": 5, "isPremium": 1],
//                                     ["image": 167, "parts": 5, "isPremium": 1],
//                                     ["image": 168, "parts": 5, "isPremium": 1]
                                    ],
                               
                               "8": [["image": 169, "parts": 7],
                                     ["image": 170, "parts": 7],
                                     ["image": 171, "parts": 6],
                                     ["image": 172, "parts": 6],
                                     ["image": 173, "parts": 7],
                                     ["image": 174, "parts": 7],
                                     ["image": 175, "parts": 7],
                                     ["image": 176, "parts": 7],
                                     ["image": 177, "parts": 7],
                                     ["image": 178, "parts": 8],
                                     ["image": 179, "parts": 7],
                                     ["image": 180, "parts": 7],
                                     ["image": 181, "parts": 8],
                                     ["image": 182, "parts": 8],
                                     ["image": 183, "parts": 8],
                                     ["image": 184, "parts": 8],
//                                     ["image": 185, "parts": 5, "isPremium": 1],
//                                     ["image": 186, "parts": 5, "isPremium": 1],
//                                     ["image": 187, "parts": 5, "isPremium": 1],
//                                     ["image": 188, "parts": 6, "isPremium": 1],
//                                     ["image": 189, "parts": 7, "isPremium": 1],
//                                     ["image": 190, "parts": 7, "isPremium": 1],
//                                     ["image": 191, "parts": 9, "isPremium": 1],
//                                     ["image": 192, "parts": 7, "isPremium": 1]
                                    ],
                               
                               "9": [["image": 193, "parts": 7],
//                                     ["image": 194, "parts": 9],
//                                     ["image": 195, "parts": 9],
                                     ["image": 196, "parts": 7],
                                     ["image": 197, "parts": 7],
                                     ["image": 198, "parts": 7],
                                     ["image": 199, "parts": 7],
                                     ["image": 200, "parts": 7],
                                     ["image": 201, "parts": 7],
                                     ["image": 202, "parts": 7],
                                     ["image": 203, "parts": 8],
                                     ["image": 204, "parts": 8],
                                     ["image": 205, "parts": 7],
                                     ["image": 206, "parts": 7],
                                     ["image": 207, "parts": 9],
                                     ["image": 208, "parts": 9],
                                     ["image": 209, "parts": 9, "isPremium": 1],
                                     ["image": 210, "parts": 9, "isPremium": 1],
//                                     ["image": 211, "parts": 8, "isPremium": 1],
//                                     ["image": 212, "parts": 8, "isPremium": 1],
//                                     ["image": 213, "parts": 5, "isPremium": 1],
//                                     ["image": 214, "parts": 5, "isPremium": 1],
//                                     ["image": 215, "parts": 12, "isPremium": 1],
//                                     ["image": 216, "parts": 12, "isPremium": 1]
                                    ],
                               
                               "10": [["image": 217, "parts": 8],
                                      ["image": 218, "parts": 8],
                                      ["image": 219, "parts": 10],
                                      ["image": 220, "parts": 12],
                                      ["image": 221, "parts": 10],
                                      ["image": 222, "parts": 10],
                                      ["image": 223, "parts": 12],
                                      ["image": 224, "parts": 10],
                                      ["image": 225, "parts": 11],
                                      ["image": 226, "parts": 11],
                                      ["image": 227, "parts": 12],
                                      ["image": 228, "parts": 12],
                                      ["image": 229, "parts": 14],
                                      ["image": 230, "parts": 14],
                                      ["image": 231, "parts": 13],
                                      ["image": 232, "parts": 13],
//                                      ["image": 233, "parts": 12, "isPremium": 1],
//                                      ["image": 234, "parts": 12, "isPremium": 1],
//                                      ["image": 235, "parts": 13, "isPremium": 1],
//                                      ["image": 236, "parts": 16, "isPremium": 1],
                                      ["image": 237, "parts": 13, "isPremium": 1],
                                      ["image": 238, "parts": 15, "isPremium": 1],
                                      ["image": 239, "parts": 15, "isPremium": 1],
                                      ["image": 240, "parts": 13, "isPremium": 1]
                                     ],
                               
                               "11": [["image": 241, "parts": 16],
                                      ["image": 242, "parts": 16],
                                      ["image": 243, "parts": 16],
                                      ["image": 244, "parts": 16],
                                      ["image": 245, "parts": 16],
                                      ["image": 246, "parts": 16],
                                      ["image": 247, "parts": 16],
                                      ["image": 248, "parts": 16],
                                      ["image": 249, "parts": 16],
                                      ["image": 250, "parts": 14],
                                      ["image": 251, "parts": 14],
                                      ["image": 252, "parts": 13],
                                      ["image": 253, "parts": 13],
                                      ["image": 254, "parts": 13],
                                      ["image": 255, "parts": 11],
                                      ["image": 256, "parts": 11],
                                      ["image": 257, "parts": 10, "isPremium": 1],
                                      ["image": 258, "parts": 10, "isPremium": 1],
                                      ["image": 259, "parts": 10, "isPremium": 1],
                                      ["image": 260, "parts": 10, "isPremium": 1],
                                      ["image": 261, "parts": 10, "isPremium": 1],
                                      ["image": 262, "parts": 10, "isPremium": 1],
                                      ["image": 263, "parts": 10, "isPremium": 1],
                                      ["image": 264, "parts": 10, "isPremium": 1]],
                               
                               "12": [["image": 265, "parts": 9],
                                      ["image": 266, "parts": 9],
                                      ["image": 267, "parts": 9],
                                      ["image": 268, "parts": 9],
                                      ["image": 269, "parts": 9],
                                      ["image": 270, "parts": 9],
                                      ["image": 271, "parts": 9],
                                      ["image": 272, "parts": 9],
                                      ["image": 273, "parts": 9],
                                      ["image": 274, "parts": 9],
                                      ["image": 275, "parts": 9],
                                      ["image": 276, "parts": 9],
                                      ["image": 277, "parts": 9],
                                      ["image": 278, "parts": 9],
                                      ["image": 279, "parts": 9],
                                      ["image": 280, "parts": 8],
                                      ["image": 281, "parts": 8, "isPremium": 1],
                                      ["image": 282, "parts": 8, "isPremium": 1],
                                      ["image": 283, "parts": 8, "isPremium": 1],
                                      ["image": 284, "parts": 8, "isPremium": 1],
                                      ["image": 285, "parts": 8, "isPremium": 1],
                                      ["image": 286, "parts": 7, "isPremium": 1],
                                      ["image": 287, "parts": 7, "isPremium": 1],
                                      ["image": 288, "parts": 4, "isPremium": 1]],
                               
                               "13": [["image": 289, "parts": 17],
                                      ["image": 290, "parts": 17],
//                                      ["image": 291, "parts": 17],
//                                      ["image": 292, "parts": 17],
                                      ["image": 293, "parts": 18],
                                      ["image": 294, "parts": 18],
                                      ["image": 295, "parts": 19],
                                      ["image": 296, "parts": 19],
                                      ["image": 297, "parts": 19],
                                      ["image": 298, "parts": 19],
                                      ["image": 299, "parts": 21],
                                      ["image": 300, "parts": 21],
                                      ["image": 301, "parts": 21],
                                      ["image": 302, "parts": 24],
                                      ["image": 303, "parts": 24],
                                      ["image": 304, "parts": 25],
                                      ["image": 305, "parts": 2, "isPremium": 1],
                                      ["image": 306, "parts": 2, "isPremium": 1],
                                      ["image": 307, "parts": 2, "isPremium": 1],
                                      ["image": 308, "parts": 2, "isPremium": 1],
                                      ["image": 309, "parts": 3, "isPremium": 1],
                                      ["image": 310, "parts": 3, "isPremium": 1],
                                      ["image": 311, "parts": 3, "isPremium": 1],
                                      ["image": 312, "parts": 3, "isPremium": 1]]
]
